title: Yuhan Zhang's Homepage
page-top-title: Yuhan Zhang
top-section-bg-text: Welcome to Yuhan Zhang's Homepage
home-subtitle: Yuhan Zhang&ensp;|&ensp;张煜涵
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
